<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Almostengr.PlaneTracker-0db6e999-034a-4219-9b55-9b233b925ecf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Almostengr.Common" Version="8.2025.5.28" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageReference Include="OpenSky" Version="1.1.0" />
    <PackageReference Include="TweetinviAPI" Version="5.0.4" />
    <PackageReference Include="X.Bluesky" Version="2.0.4" />
  </ItemGroup>
</Project>
